spring:
  cloud:
    #配置计算机名
    consul:
      discovery:
        hostname: 192.168.31.222   # 配置实例地址
  redis:
    host: 192.168.63.130
    port: 6379
    database: 2
  data:
    mongodb:
      uri: mongodb://auth:auth@192.168.63.130:27017,192.168.63.130:27018,192.168.63.130:27019,192.168.63.130:27020/auth?replicaSet=MongoSets
      auto-index-creation: true




#logging:
#  level:
#    org:
#      springframework: trace
#debug: true
#trace: true