
spring:
  application:
    name: test11
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        health-check-path: /actuator/health  # 检测实例健康
        health-check-interval: 10s   # 每隔10s检查
        hostname: localhost    # 配置实例地址
        register: true  # 自动注册
#        service-name: ${spring.application.name} # 实例名称
#        instance-id: ${spring.application.name}:${server.port}
        service-name: test-service # 实例名称
        instance-id: test-id
      host: 127.0.0.1
      port: 7000


#调试或者输出日志
#logging:
#  file:
#    name: logs/${project.artifactId}.log
#debug: true


