#允许端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"



limit:
  roles:
    firewall:
      url: "/ucenter/*"
      policy:
        cycleTime: 10
        accessCount: 10
        blockTime: 60
    service:
      url: "/config/*,/gateway/*,/push/*,/consul/*"
    actuator:
      url: "/actuator,*/actuator/*"
      exclusion: "/actuator/health"
    manager:
      url: "*/manager/*,*/endpoints/*"
      allowIp: "127.0.0.1"
    openapi:
      url: "*/openapi/*"
      exclusion: "/openapi/*"


spring:
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
#    consul:
#      discovery:
#        hostname: 192.168.8.225
#        prefer-ip-address: false
  redis:
    host: 192.168.8.226
    port: 6379
    database: 6


logging:
  file:
    name: logs/${project.artifactId}.log
#  level:
#    com:
#      github:
#        microservice:
#          gateway:
#            core: debug
#    org:
#      springframework:
#        cloud:
#          netflix: trace
#          gateway: trace
#debug: true
#trace: true